apiVersion: apps/v1
kind: Deployment
metadata:
  name: GinMasterReWi
  labels:
    app.kubernetes.io/name: GinMasterReWi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: GinMasterReWi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: GinMasterReWi
    spec:
      serviceAccountName: GinMasterReWi
      containers:
      - name: GinMasterReWi
        image: xmadmin/GinMasterReWi:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
