apiVersion: v1
kind: ServiceAccount
metadata:
  name: GinMasterReWi
  labels:
    app.kubernetes.io/name: GinMasterReWi
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: GinMasterReWi-rolebinding
  labels:
    app.kubernetes.io/name: GinMasterReWi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: GinMasterReWi
