apiVersion: v1
kind: Service
metadata:
  name: GinMasterReWi
  labels:
    app.kubernetes.io/name: GinMasterReWi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: GinMasterReWi
